Models/ErrorViewModel.cs
namespace Checkpont2.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/User.cs
using System.ComponentModel.DataAnnotations;

namespace Checkpont2.Models
{
    public class User
    {
        [Key]
        public int Id { get; set; }
        public String UserName { get; set; } = String.Empty;
        public String UserEmail { get; set; } = String.Empty;
        public String UserPassword { get; set; } = String.Empty;
        public String UserOccupation { get; set; } = String.Empty;
    }
}

Controllers/CadastroController.cs
using Checkpont2.Data;
using Checkpont2.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Checkpont2.Controllers
{
    public class CadastroController : Controller
    {
        private readonly DataContext _context;

        public CadastroController(DataContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult SignUp(User request)
        {
            var user = _context.TB_USERS.FirstOrDefault(x => x.UserEmail == request.UserEmail);
            if (user != null)
            {
                return BadRequest("User already registered");
            }

            User newUser = new User
            {
                UserEmail = request.UserEmail,
                UserName = request.UserName,
                UserPassword = request.UserPassword,
                UserOccupation = request.UserOccupation
            };

            _context.Add(newUser);
            _context.SaveChanges();

            return RedirectToAction("SignUpSuccess", new { userId = newUser.Id } );

        }

        public IActionResult SignUpSuccess(int userId)
        {                                                    
            User userFound = _context.TB_USERS.FirstOrDefault(u => u.Id == userId);

            if (userFound == null)
            {
                return BadRequest("User doesn't exist");
            }            
            
            return View(userFound);
        }

        public IActionResult Update(int id)
        {
            var user = _context.TB_USERS.FirstOrDefault(x => x.Id == id);
            if (user == null)
            {
                return BadRequest("User doesn't exist");
            }

            return View(user);

        }

        public IActionResult UpdateUser(User request)
        {
            var user = request;

            user.Id = request.Id;
            user.UserEmail = request.UserEmail;
            user.UserName = request.UserName;
            user.UserPassword = request.UserPassword;
            user.UserOccupation = request.UserOccupation;            

            _context.Update(user);            
            _context.SaveChanges();

            return RedirectToAction("SignUpSuccess", new { userId = user.Id });

        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

    }
}

Controllers/HomeController.cs
using Checkpont2.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Checkpont2.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/LoginController.cs
using Checkpont2.Data;
using Checkpont2.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Checkpont2.Controllers
{
    public class LoginController : Controller
    {
        private readonly DataContext _context;

        public LoginController(DataContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult LoginValid(User request)
        {
            var user = _context.TB_USERS.FirstOrDefault(x => x.UserEmail == request.UserEmail);
            if (user == null)
            {
                return BadRequest("Non-existent user email");
            }

            if (user.UserPassword != request.UserPassword)
            {
                return BadRequest("Incorrect password");
            }
            
            return View(user);
        }

        public IActionResult Delete(User request)
        {
            var user = _context.TB_USERS.FirstOrDefault(x => x.Id == request.Id);

            if (user != null) 
            {
                _context.TB_USERS.Remove(user);
                _context.SaveChanges();
            }
            
            return View(user);
        }


    }
}

Controllers/UsersController.cs
using Checkpont2.Data;
using Microsoft.AspNetCore.Mvc;

namespace Checkpont2.Controllers
{
    public class UsersController:Controller
    {
        private readonly DataContext _context;

        public UsersController(DataContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var users = _context.TB_USERS.ToList();
            return View(users);
        }
    }
}

Views/Cadastro/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="container">

    <form asp-controller="Cadastro" asp-action="SignUp" method="post">
        <div class="form-group row mb-2">
            <label for="UserEmail" class="col-sm-2 col-form-label">Email:</label>
            <div class="col-sm-10">
                <input name="UserEmail" type="email" class="form-control" id="exampleFormControlInput1" placeholder="rafael@fiap.com" style="width: 500px;">
            </div>
        </div>
        <div class="form-group row mb-2">
            <label for="UserName" class="col-sm-2 col-form-label">User name:</label>
            <div class="col-sm-10">
                <input name="UserName" class="form-control" type="text" placeholder="rafael123" style="width: 300px;">
            </div>
        </div>
        <div class="form-group row mb-2">
            <label for="UserPassword" class="col-sm-2 col-form-label">Password:</label>
            <div class="col-sm-10">
                <input name="UserPassword" type="password" class="form-control" style="width: 220px;">
            </div>
        </div>
        <div class="form-group row mb-2">
            <label for="UserOccupation" class="col-sm-2 col-form-label">Occupation:</label>
            <div class="col-sm-10">
                <input name="UserOccupation" class="form-control" type="text" placeholder="Data Analyst" style="width: 200px;">
            </div>
        </div>

        <div class="form-group row mb-2">
            <div class="col-sm-10 offset-sm-2 me-10">
                <button type="submit" class="btn btn-primary">Save</button>
            </div>
        </div>
    </form>

</div>

Views/Cadastro/SignUpSuccess.cshtml
@model User

<style>
    .form-group {
        display: flex;
        flex-direction: row;
        align-items: center;
        margin-bottom: 10px;
    }

    .form-group label {
        text-align: right;
        width: 150px; 
        margin-right: 10px;
    }

    .tamanhoInput {
        width: 400px;
    }
</style>

<div>
    <h3>Dados Cadastrados</h3>
    <div class="form-group">
        <label for="userName">Nome de Usuário:</label>
        <input type="text" id="userName" class="border-2 tamanhoInput" name="userName" value="@Model.UserName" />
    </div>
    <div class="form-group">
        <label for="userEmail">E-mail:</label>
        <input type="text" id="userEmail" class="border-2 tamanhoInput" name="userEmail" value="@Model.UserEmail" />
    </div>
    <div class="form-group">
        <label for="userOccupation">Ocupação:</label>
        <input type="text" id="userOccupation" class="border-2 tamanhoInput" name="userOccupation" value="@Model.UserOccupation" />
    </div>
</div>

Views/Cadastro/Update.cshtml
@model User

<style>
    .form-group {
        display: flex;
        flex-direction: row;
        align-items: center;
        margin-bottom: 10px;
    }

        .form-group label {
            text-align: right;
            width: 150px;
            margin-right: 10px;
        }

    .tamanhoInput {
        width: 400px;
    }
</style>

<div>
    <h3>Your Information</h3>
    <form asp-controller="Cadastro" asp-action="UpdateUser" method="put">
    <div class="form-group">
        <label for="userName">User name:</label>
        <input type="text" id="userName" class="border-2 tamanhoInput" name="userName" value="@Model.UserName" />
    </div>
    <div class="form-group">
        <label for="userEmail">E-mail:</label>
        <input type="text" id="userEmail" class="border-2 tamanhoInput" name="userEmail" value="@Model.UserEmail" />
    </div>
    <div class="form-group">
        <label for="userOccupation">Occupation:</label>
        <input type="text" id="userOccupation" class="border-2 tamanhoInput" name="userOccupation" value="@Model.UserOccupation" />
    </div>
        <input type="hidden" id="userPassword" class="border-2 tamanhoInput" name="userPassword" value="@Model.UserPassword" />
        <input type="hidden" id="id" class="border-2 tamanhoInput" name="id" value="@Model.Id" />
        <div class="form-group row mb-2">
            <div class="col-sm-10 offset-sm-2 me-10">
                <button type="submit" class="btn btn-primary">Update</button>
            </div>
        </div>
    </form>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<div class="text-center">
    <h1>CRUD application</h1>
    <h3><a asp-controller="Cadastro" asp-action="Index">Start here</a></h3>
</div>

Views/Login/Delete.cshtml
@model User


<h2>Account deleted</h2>
<p>Bye @Model.UserName</p>

Views/Login/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="container">
    <h3 class="text-center mb-3">Sign in </h3>
    <form asp-controller="Login" asp-action="LoginValid" method="post">
        <div class="form-group row mb-2">
            <label for="UserEmail" class="col-sm-2 col-form-label">Email:</label>
            <div class="col-sm-10">
                <input name="UserEmail" type="email" class="form-control" id="exampleFormControlInput1" placeholder="rafael@fiap.com" style="width: 500px;">
            </div>
        </div>        
        <div class="form-group row mb-2">
            <label for="UserPassword" class="col-sm-2 col-form-label">Password:</label>
            <div class="col-sm-10">
                <input name="UserPassword" type="password" class="form-control" style="width: 220px;">
            </div>
        </div>        
        <div class="form-group row mb-2">
            <div class="col-sm-10 offset-sm-2 me-10">
                <button type="submit" class="btn btn-primary">Login</button>
            </div>
        </div>
    </form>

</div>

Views/Login/LoginValid.cshtml
@model User

<style>
    .form-group {
        display: flex;
        flex-direction: row;
        align-items: center;
        margin-bottom: 10px;
    }

        .form-group label {
            text-align: right;
            width: 150px;
            margin-right: 10px;
        }

    .tamanhoInput {
        width: 400px;
    }
</style>

<div>
    <h3>Login Success</h3>  
    <form asp-controller="Login" asp-action="Delete" method="delete">
        <input type="hidden" id="id" class="border-2 tamanhoInput" name="id" value="@Model.Id" />
        <div class="form-group">
            <label for="userEmail">E-mail:</label>
            <input type="text" id="userEmail" class="border-2 tamanhoInput" name="userEmail" value="@Model.UserEmail"/>
        </div>
        <div class="form-group">
                <label for="userOccupation">Occupation:</label>
            <input type="text" id="userOccupation" class="border-2 tamanhoInput" name="userOccupation" value="@Model.UserOccupation"/>
        </div>
        <div class="form-group row mb-2">
            <div class="col-sm-10 offset-sm-2 me-10">
                <button type="submit" class="btn btn-primary">Delete account</button>
            </div>
        </div>
    </form>
    <form asp-controller="Cadastro" asp-action="Update">
        <input type="hidden" id="id" class="border-2 tamanhoInput" name="id" value="@Model.Id" />
        <div class="form-group row mb-2">
            <div class="col-sm-10 offset-sm-2 me-10">
                <button class="btn btn-primary">Update your registration information</button>
            </div>
        </div>
    </form>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Checkpont2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Checkpont2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Checkpont2</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cadastro" asp-action="Index">Sign in</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Index">Login</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Users</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Checkpont2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Users/Index.cshtml
@model List<Checkpont2.Models.User> 
@{

}<head>
    <h3>Users List</h3>
    <style>
        table {
            width: 100%;
            border-collapse: collapse;
        }

        th, td {
            padding: 8px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }

        th {
            background-color: #f2f2f2;
        }

        tr:hover {
            background-color: #f5f5f5;
        }
    </style>
</head>
<table>
    <thead>
        <tr>
           
            <th>Email</th>
            <th>UserName</th>
            <th>Occupation</th>
            
        </tr>
    </thead>
    <tbody>
        @foreach (var user in Model)
        {
            <tr>
                
                <td>@user.UserEmail</td>
                <td>@user.UserName</td>
                <td>@user.UserOccupation</td>
              
            </tr>
        }
    </tbody>
    </table>